const states: string[] = [
  'ABIA',
  'ADAMAWA',
  'AKWA-IBOM',
  'ANAMBRA',
  'BAUCHI',
  'BENUE',
  'BORNO',
  'BAYELSA',
  'CROSS RIVER',
  'DELTA',
  'EBONYI',
  'EDO',
  'EKITI',
  'ENUGU',
  'FCT-ABUJA',
  'GOMBE',
  'JIGAWA',
  'IMO',
  'KADUNA',
  'KEBBI',
  'KANO',
  'KOGI',
  'LAGOS',
  'KASTINA',
  'KWARA',
  'NASARAWA',
  'NIGER',
  'OGUN',
  'ONDO',
  'RIVERS',
  'OYO',
  'OSUN',
  'SOKOTO',
  'PLATEAU',
  'TARABA',
  'YOBE',
  'ZAMFARA',
];

const compoundStatesData: {
  displayName: string;
  route: string;
  name: string;
  zone: string;
}[] = [
  {displayName: 'Abia', route: 'abia', name: 'state', zone: 'SE'},
  {displayName: 'Adamawa', route: 'adamawa', name: 'state', zone: 'NE'},
  {displayName: 'Akwa-Ibom', route: 'akwa-ibom', name: 'state', zone: 'SS'},
  {displayName: 'Anambra', route: 'anambra', name: 'state', zone: 'SE'},
  {displayName: 'Bauchi', route: 'bauchi', name: 'state', zone: 'NE'},
  {displayName: 'Bayelsa', route: 'bayelsa', name: 'state', zone: 'SS'},
  {displayName: 'Benue', route: 'benue', name: 'state', zone: 'NC'},
  {displayName: 'Borno', route: 'borno', name: 'state', zone: 'NE'},
  {displayName: 'Cross River', route: 'cross-river', name: 'state', zone: 'SS'},
  {displayName: 'Delta', route: 'delta', name: 'state', zone: 'SS'},
  {displayName: 'Ebonyi', route: 'ebonyi', name: 'state', zone: 'SE'},
  {displayName: 'Edo', route: 'edo', name: 'state', zone: 'SS'},
  {displayName: 'Ekiti', route: 'ekiti', name: 'state', zone: 'SW'},
  {displayName: 'Enugu', route: 'enugu', name: 'state', zone: 'SE'},
  {displayName: 'Gombe', route: 'gombe', name: 'state', zone: 'NE'},
  {displayName: 'Imo', route: 'imo', name: 'state', zone: 'SE'},
  {displayName: 'Jigawa', route: 'jigawa', name: 'state', zone: 'NW'},
  {displayName: 'Kaduna', route: 'kaduna', name: 'state', zone: 'NW'},
  {displayName: 'Kano', route: 'kano', name: 'state', zone: 'NW'},
  {displayName: 'Katsina', route: 'katsina', name: 'state', zone: 'NW'},
  {displayName: 'Kebbi', route: 'kebbi', name: 'state', zone: 'NW'},
  {displayName: 'Kogi', route: 'kogi', name: 'state', zone: 'NC'},
  {displayName: 'Kwara', route: 'kwara', name: 'state', zone: 'NC'},
  {displayName: 'Lagos', route: 'lagos', name: 'state', zone: 'SW'},
  {displayName: 'Nasarawa', route: 'nasarawa', name: 'state', zone: 'NC'},
  {displayName: 'Niger', route: 'niger', name: 'state', zone: 'NC'},
  {displayName: 'Ogun', route: 'ogun', name: 'state', zone: 'SW'},
  {displayName: 'Ondo', route: 'ondo', name: 'state', zone: 'SW'},
  {displayName: 'Osun', route: 'osun', name: 'state', zone: 'SW'},
  {displayName: 'Oyo', route: 'oyo', name: 'state', zone: 'SW'},
  {displayName: 'Plateau', route: 'plateau', name: 'state', zone: 'NC'},
  {displayName: 'Rivers', route: 'rivers', name: 'state', zone: 'SS'},
  {displayName: 'Sokoto', route: 'sokoto', name: 'state', zone: 'NW'},
  {displayName: 'Taraba', route: 'taraba', name: 'state', zone: 'NE'},
  {displayName: 'Yobe', route: 'yobe', name: 'state', zone: 'NE'},
  {displayName: 'Zamfara', route: 'zamfara', name: 'state', zone: 'NW'},
  {displayName: 'FCT - Abuja', route: 'FCT - ABUJA', name: 'state', zone: 'NC'},
];

export {states, compoundStatesData};
