export const SDGs = [
  "NO POVERTY",
  "ZERO HUNGER",
  "GOOD HEALTH & WELL-BEING",
  "QUALITY EDUCATION",
  "GENDER EQUALITY",
  "CLEAN WATER & SANITATION",
  "AFFORDABLE & CLEAN ENERGY",
  "DECENT WORK & ECONOMIC GROWTH",
  "INDUSTRY, INNOVATION & INFRASTRUCTURE",
  "REDUCED INEQUALITY",
  "SUSTAINABLE CITIES & COMMUNITIES",
  "RESPONSIBLE CONSUMPTION & PRODUCTION",
  "CLIMATE ACTION",
  "LIFE BELOW WATER",
  "LIFE ON LAND",
  "PEACE & JUSTICE STRONG INSTITUTIONS",
  "PARTNERSHIPS TO ACHIEVE THE GOAL"
];
