export const SECTORS = [
	"AGRICULTURE",
	"MINING AND QUARRYING",
	"MANUFACTURING",
	"ELECTRICITY, GAS, STEAM AND AIR CONDITIONING SUPPLY",
	"WATER SUPPLY, SEWERAGE, WASTE MANAGEMENT AND REMEDIATION",
	"CONSTRUCTION",
	"TRADE",
	"ACCOMMODATION AND FOOD SERVICES",
	"TRANSPORTATION AND STORAGE",
	"INFORMATION AND COMMUNICATION",
	"ARTS, ENTERTAINMENT AND RECREATION",
	"REAL ESTATE SERVICES",
	"FINANCIAL AND INSURANCE",
	"PROFESSIONAL, SCIENTIFIC AND TECHNICAL SERVICES",
	"ADMINISTRATIVE & SUPPORT SERVICES",
	"PUBLIC ADMINISTRATION",
	"EDUCATION",
	"HUMAN HEALTH AND SOCIAL SERVICES",
	"OTHER SERVICES",
]

export const PLANS = ["MTNDP", "ERGP"]
